[package]
name = "vlitz-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
vlitz-shared = { path = "../shared" }
frida-rust = "0.4"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4" 